### ISSUE TITLE
fails to compile on 8.4.2 and probably (8.4.1)

### ISSUE THREAD

**Issue by GeorgeCo** [bscarlet/llvm-general#209]
fails to compile on 8.4.2 and probably (8.4.1)

cabal install -j5 llvm-general
...
Failed to install llvm-general-pure-3.5.0.0
Build log ( /Users/gcolpitts/.cabal/logs/ghc-8.4.2/llvm-general-pure-3.5.0.0-K5dZ1oCl0eTJBIlvbqyDx8.log ):
cabal: Entering directory '/var/folders/9b/rh4y2gy92hgdb6ktv4df1jv00000gn/T/cabal-tmp-72872/llvm-general-pure-3.5.0.0'
Configuring llvm-general-pure-3.5.0.0...
Warning: The package has an extraneous version range for a dependency on an
internal library: llvm-general-pure ==3.5.0.0. This version range includes the
current package but isn't needed as the current package's library will always
be used.
...
Preprocessing library for llvm-general-pure-3.5.0.0..
Building library for llvm-general-pure-3.5.0.0..
...
[27 of 28] Compiling LLVM.General.Internal.PrettyPrint ( src/LLVM/General/Internal/PrettyPrint.hs, dist/build/LLVM/General/Internal/PrettyPrint.o )

src/LLVM/General/Internal/PrettyPrint.hs:61:10: error:
    • No instance for (Semigroup QTree)
        arising from the superclasses of an instance declaration
    • In the instance declaration for ‘Monoid QTree’
   |
61 | instance Monoid QTree where
...

**Comment by andrewerf** [comment]
I've faced this issue today. Has it not been fixed since then? Did you find workaround?
